### ISSUE TITLE
connection diagram of the programmer

### ISSUE THREAD

**Issue by kraa965** [janick/WT32-SqLn#1]
Hi, thanks for your article, it helped me a lot to figure out that usb-c was not created for downloading a sketch
But I have a question, how to connect the programmer in wt32-sc01 plus
![image](https://user-images.githubusercontent.com/33607882/212756475-d294586d-33aa-4329-bc78-f1118c1a33e6.png)
it seemed to me mlm on the attached screenshot, you have changed the rx and tx places, could you attach a clear connection diagram of the programmer?
and I understand that you are powering wt32-sc01 plus from 3v3?

**Comment by janick** [comment]
If you read the text in the 1st paragraph [here](https://github.com/janick/WT32-SqLn#using-your-own-usb-to-serial-board) it says to connect Tx with Rx, Rx with Tx, GND with GND, and GPIO0 with GND.

| WT32-SC01 Pin | Serial Board Pin | Remark |
| ---------------- | ---------------- | ------- |
| 5V | VCC | Optional but not sufficient to power WT32 |
| Tx | Rx | Max 3.3V |
| Rx | Tx | Max 3.3V |
| GND | GND |
| GPIO0 | GND |

It also says (just below the photo) that you cannot power the WT32-SC01+ from the serial programmer because there isn't enough *ooomph*. You have to power it from its own USB-C port. The 3.3V selector is for the TTL logic value, and like all ESP32 signals, the TX/RX signals are 3.3V not 5V.

**Comment by kraa965** [comment]
thank you, I really appreciate the explanation
