### ISSUE TITLE
Wake-up Pin

### ISSUE THREAD

**Issue by kraa965** [janick/WT32-SqLn#5]
hi, esp has a function esp_sleep_enable_ext0_wakeup, tell me which pin is responsible for the output from deep sleep?

**Comment by janick** [comment]
I would refer to [this article](https://randomnerdtutorials.com/esp32-external-wake-up-deep-sleep/) and use one of the [exposed GPIO pins](https://github.com/janick/WT32-SqLn#gpios).

The article uses the Arduino framework whereas this example uses IDF but since the former builds on the latter, it is possible to accomplish there as well. [This article](https://esp32tutorials.com/esp32-esp-idf-deep-sleep-modes-wake-up-sources/) might be a good starting point.

**Comment by kraa965** [comment]
perhaps I did not correctly compose the question, for example, some screens have an IRQ output, which, when pressed on the touch screen, brings the board out of deep sleep, just look at the documentation of wt32 sc01 plus, I did not see this output, so I decided to find out from you after reading your article

**Comment by janick** [comment]
That would be a question for Wireless Tag...

There is a board schematic [on page 8 of the User Guide](https://github.com/janick/WT32-SqLn/blob/main/docs/WT32-SC01-Plus-V1.3-EN.pdf) and it shows a "TP_INT" signal on the LCD port connected to "IO7" on the ESP32. Maybe that would work using the approach shown above?

**Comment by kraa965** [comment]
I tried to use this pin, but for some reason it does not respond to touch, esp does not come out of deep sleep
