### ISSUE TITLE
Error on build project

### ISSUE THREAD

**Issue by visued** [janick/WT32-SqLn#9]
Hi, thanks for the guide bro,

I need help for the build project.
This is my config for export path ui in squareline:
![image](https://github.com/janick/WT32-SqLn/assets/5278800/adf288d3-edcd-451f-a764-3894ac7113ce)

I I followed the steps described on your page, however, trying to execute the build command `idf.py build` is returning an error in the ui.c file when you need these methods:
![image](https://github.com/janick/WT32-SqLn/assets/5278800/3f8f3d65-bf37-4cfe-9d2b-91084a5decf5)

This is error in terminal:
![image](https://github.com/janick/WT32-SqLn/assets/5278800/03f4f1a6-0721-4f70-b654-4e2660a5dc3d)

Any idea how to solve this ?

Best regards

**Comment by janick** [comment]
Yes. The more recent version of Squareline Studio exports the screens UI files in the "screens" subdirectory instead of a flat directory.

You need to modify the main/CMakeLists.txt file to make sure it lists the additional files under the correct path:

```
idf_component_register(SRCS "main.cpp" "ui/ui.c" "ui/ui_helpers.c" "ui/screens/ui_Main_Screen.c" "ui/screens/ui_Splash_Screen.c"
```

I've just pushed a fix so a simple 'pull' on your end should fix the issue.

Squareline Studio generates a CMakeLists.txt file in the export directory that I'm sure there is a way for the higher level one to include and avoid all these explicit paths problems, but not being a experienced cmake user, I do not know the right way to do it.

**Comment by visued** [comment]
Owww very thanks bro, works fine!
